compute_environment: LOCAL_MACHINE
distributed_type: FSDP
mixed_precision: bf16
num_processes: 8
num_machines: 1
machine_rank: 0
fsdp_config:
  sharding_strategy: 1                # FULL_SHARD
  offload_params: false
  offload_optimizer: false
  state_dict_type: FULL_STATE_DICT
  sync_module_states: true
  use_orig_params: true
  forward_prefetch: true
  limit_all_gathers: true
  activation_checkpointing: true
  auto_wrap_policy: TRANSFORMER_BASED_WRAP
  